name: Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: [bug, triage]
body:
  - type: markdown
    attributes:
      value: |
        Before moving on you should have performed enough troubleshooting to rule out common issues. For example,
        
        * compare the behavior with other similar projects such as NET-SNMP.
        * capture SNMP packets with a tool like Wireshark.
        * enable [built-in PySNMP debugging](https://www.pysnmp.com/pysnmp/examples/#using-these-examples) to see what's happening.
        
        If troubleshooting does not reveal very useful information or you need further assistance, please fill out the bug report below.
        
        To report an issue privately (such as security vulnerabilities), please write to [us](mailto:support@lextudio.com).
        
        Thanks for taking the time!
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: Tell us what you expected to happen.
      placeholder: Tell us what you expected to happen.
      value: "I expected this,"
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: Tell us what you see!
      placeholder: Tell us what you see!
      value: "But a bug happened like this,"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Detailed steps
      description: Detailed steps to reproduce the problem.
      placeholder: Detailed steps to reproduce the problem.
      value: "The steps are,"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Python package information
      description: What version(s) of our package(s) are you using? You can usually find such information from `pip list` or `pip freeze`.
      placeholder: xxx.0.0
    validations:
      required: true
  - type: input
    id: platform
    attributes:
      label: Operating system information
      description: What version(s) of operating system(s) are you using?
      placeholder: Windows, macOS, and/or Linux? What version(s)?
    validations:
      required: true
  - type: input
    id: python
    attributes:
      label: Python information
      description: What version(s) of Python are you using?
      placeholder: xxx.0.0
    validations:
      required: true
  - type: textarea
    id: conf
    attributes:
      label: (Optional) Contents of your test script
      description: Paste the entire test script here if you didn't paste your test script above. This will be automatically formatted into code, so no need for backticks.
      render: python
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output (for example, the error messages showed in the console). This will be automatically formatted into code, so no need for backticks.
      render: shell
